# sets up minio and mongo

version: '3.9'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-17T01-15-57Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  mongo_data:
